# Conexión a la Base de Datos PostgreSQL
# "db" es el nombre del servicio en el docker-compose.yml
spring.datasource.url=jdbc:postgresql://db:5432/crud_users
spring.datasource.username=admin
spring.datasource.password=admin_password

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración del servidor
server.port=8080